// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMhnPeshin7F2OknMAF3a2NpkPLPbSQA',
    appId: '1:293685830298:web:03bcb562cfb2ba8a9f7523',
    messagingSenderId: '293685830298',
    projectId: 'fir-demo-67917',
    authDomain: 'fir-demo-67917.firebaseapp.com',
    storageBucket: 'fir-demo-67917.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA69xOOSavtYmrOd6W2lC7Zt3-ROd5iyfA',
    appId: '1:293685830298:android:b52ac09ef659befe9f7523',
    messagingSenderId: '293685830298',
    projectId: 'fir-demo-67917',
    storageBucket: 'fir-demo-67917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd86At-hyB_NNeRqiCAZ1QAdETK6RwfuM',
    appId: '1:293685830298:ios:c43a5e65f9d552f39f7523',
    messagingSenderId: '293685830298',
    projectId: 'fir-demo-67917',
    storageBucket: 'fir-demo-67917.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd86At-hyB_NNeRqiCAZ1QAdETK6RwfuM',
    appId: '1:293685830298:ios:c43a5e65f9d552f39f7523',
    messagingSenderId: '293685830298',
    projectId: 'fir-demo-67917',
    storageBucket: 'fir-demo-67917.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEMhnPeshin7F2OknMAF3a2NpkPLPbSQA',
    appId: '1:293685830298:web:a0b7a76a6b6665929f7523',
    messagingSenderId: '293685830298',
    projectId: 'fir-demo-67917',
    authDomain: 'fir-demo-67917.firebaseapp.com',
    storageBucket: 'fir-demo-67917.firebasestorage.app',
  );

}